[package]
name = "mqtt-messenger"
version = "0.1.0"
edition = "2024"

[dependencies]
rumqttc = "0.24.0"
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11.3"
anyhow = "1.0"
