[messenger_config]

[cloud_cfg]
client_id = "mqtt-messenger-client-mqtt-ws"
version = "V3"
broker = "localhost"
port = 8080
protocol = "ws"
username = ""
password = ""
sub_cloud_topics = ["cloud/into-edge/test-topic"]

[edge_cfg]
broker = "localhost"
port = 6379
db = 0
_password = ""
sub_edge_topics = ["cloud/test-topic"]
