[cloud_cfg]
client_id = "mqtt-messenger-client-1"
version = "V3"                              # V3 or V5
broker = "localhost"
port = 8883
protocol = ""                               # Options: "tcp"(default), "ws"
sub_topics = ["cloud/into-edge/test-topic"]

[cloud_cfg.auth]
# Can enable BOTH basic and mtls if needed
basic_enabled = false
mtls_enabled = true

# --- Basic Auth Fields (conditional) ---
[cloud_cfg.auth.basic] # Active if basic_enabled = true
username = ""
password = ""

# --- mTLS Fields (conditional) ---
[cloud_cfg.auth.mtls] # Active if mtls_enabled = true
ca_file = "certs/ca.crt"
cert_file = "certs/client.crt"
key_file = "certs/client.key"

[edge_cfg]
broker = "localhost"
port = 6379
db = 0
sub_topics = ["cloud/test-topic"]

[edge_cfg.auth]
# Can enable basic and mtls if needed
basic_enabled = true
mtls_enabled = true

# --- Basic Auth Fields (conditional) ---
[edge_cfg.auth.basic] # Active if basic_enabled = true
username = "user"
password = "password"

# --- mTLS Fields (conditional) ---
[edge_cfg.auth.mtls] # Active if mtls_enabled = true
ca_file = "certs/ca.crt"
cert_file = "certs/client.crt"
key_file = "certs/client.key"
